# Generated by Django 3.1.2 on 2020-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=10)),
            ],
        ),
    ]
