# Generated by Django 3.1.2 on 2020-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpumetric',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
